### ISSUE TITLE
Updates for `az ad` breaking changes.

### ISSUE THREAD

**Issue by ckittel** [mspnp/serverless-reference-implementation#103] opened 2022-06-06 15:08 UTC
This reference implementation needs updates to support the changes to `az ad app create` (and potentially other commands) to work on latest az cli, due to the breaking changes introduced in 2.37.0.

https://docs.microsoft.com/cli/azure/microsoft-graph-migration

**Comment by oscarcoding** [comment] 2022-08-21 22:23
The breaking changes caused by the migration to Microsoft.Graph mentioned above have made this project unusable for now unfortunately. The command for creating the API_APP does not work:

```
# Create the application registration, defining a new application role and requesting access to read a user using the Graph API
export API_APP_ID=$(az ad app create --display-name $API_APP_NAME --oauth2-allow-implicit-flow true \
--native-app false --reply-urls http://localhost --identifier-uris "http://$API_APP_NAME" \
--app-roles '  [ {  "allowedMemberTypes": [ "User" ], "description":"Access to device status", "displayName":"Get Device Status", "isEnabled":true, "value":"GetStatus" }]' \
--required-resource-accesses '  [ {  "resourceAppId": "00000003-0000-0000-c000-000000000000", "resourceAccess": [ { "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d", "type": "Scope" } ] }]' \
--query appId --output tsv)
```

From reading the [migration docs](https://docs.microsoft.com/cli/azure/microsoft-graph-migration), it looks like the command should be updated to read:

```
export API_APP_ID=$(az ad app create --display-name $API_APP_NAME --enable-access-token-issuance true \
--is-fallback-public-client false --web-redirect-uris http://localhost --identifier-uris "http://$TENANT_NAME.onmicrosoft.com/$API_APP_NAME" \
--app-roles '  [ {  "allowedMemberTypes": [ "User" ], "description":"Access to device status", "displayName":"Get Device Status", "isEnabled":true, "value":"GetStatus" }]' \
--required-resource-accesses '  [ {  "resourceAppId": "00000003-0000-0000-c000-000000000000", "resourceAccess": [ { "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d", "type": "Scope" } ] }]' \
--query appId --output tsv)
```

Which does create the API_APP successfully.  However the SPA deployment expects the old method to have created a field `oauth2Permissions.[user_impersonation].id`:

```
export API_IMPERSONATION_PERMISSION=$(az ad app show --id $API_APP_ID --query "oauth2Permissions[?value == 'user_impersonation'].id" --output tsv)
```

But the updated create command only creates a field `api.oauth2PermissionScopes`, which has a value of `[]`


```
"api": {
    "acceptMappedClaims": null,
    "knownClientApplications": [],
    "oauth2PermissionScopes": [],
    "preAuthorizedApplications": [],
    "requestedAccessTokenVersion": 2
  },
 ```

There is no field `oauth2Permissions` in the manifest - have checked via the cli with `az ad app show --id $API_APP_ID` and by manually looking at the manifest editor in the Azure UI.

So therefore the project is currently uninstallable until the breaking changes are addressed.

**Comment by ckittel** [comment] 2022-08-22 13:54
@hallihan can we get this one through the CS pipeline to be resolve?

**Comment by hallihan** [comment] 2022-08-22 18:00
Internal work item: https://dev.azure.com/ceapex/Content%20Planning/_workitems/edit/695185

**Comment by v-fearam** [comment] 2022-10-17 14:42
Fixed on https://github.com/mspnp/serverless-reference-implementation/pull/109

**Closed** 2022-10-17 14:57 UTC
