### ISSUE TITLE
Instalation Failure: namespace not active

### ISSUE THREAD

**Issue by rgardler** [mspnp/serverless-reference-implementation#30] opened 2019-02-16 19:59 UTC
When following the installation steps I get an error that the eventhub namespace is not active:

```
$ az group deployment create    -g ${RESOURCEGROUP}    --template-file azuredeploy-backend-functionapps.json    --parameters appName=${APPNAME}    appInsightsLocation=${APP_INSIGHTS_LOCATION}    cosmosDatabaseName=${COSMOSDB_DATABASE_NAME}    
cosmosDatabaseCollection=${COSMOSDB_DATABASE_COL}

Deployment failed. Correlation ID: 6fc6d58b-806b-487c-923c-090f2b6ea172. {
  "error": {
    "message": "The namespace jamstkun3oocvn3boxu-ns in subscription REDACTED is not active, its current state is Created. CorrelationId: c9d81846-2026-472f-8fd7-e859589fe6b9",
    "code": "NotFound"
  }
}
```

**Comment by rgardler** [comment] 2019-02-16 20:35
Rerunning the deployment will work the second time, assuming you leave long enough for the namespace to become active (for me about 30 seconds)

**Comment by jocontr** [comment] 2020-05-13 18:37
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [218973](https://dev.azure.com/ceapex/pnp/_workitems/edit/218973)

**Comment by kirpasingh** [comment] 2020-05-26 19:26
Thank you @rgardler! It may be due to updates/improvements in the resource manager engine in the interim, but I can't repro this issue. 

The only change I made is to use ```az deployment group``` since ```az group deployment``` is being deprecated and produces a warning, but that could not have caused the issue you reported. 

All dependencies (in the deployment template) look to be in order. 

I'm closing this issue for now as it seems that either you were experiencing a transitive failure or the resource manager has been updated! Please feel free to reopen, in case you're able to repro, with necessary steps to reproduce.

**Closed by kirpasingh** 2020-05-26 19:26 UTC
